baseURL = "https://navinkarkera.github.io/"
languageCode = "en-us"
theme = "sada"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
name = "Navin Karkera"
title = "Resume"
author = "Navin Karkera"
description = "Full Stack Developer"
copyright = "Custom copyright message"
theme = "dark" # `dark` or `light`
useResources = false

# Profile section
[params.profile]
name = "Navin Karkera"
photo = "images/profile.jpg"
email = "navinkarkera@disroot.org"
mobile = "+91 8655861306"

# Section for links to social websites
[params.social]
title = "Links"

[[params.social.list]]
icon = "fab fa-linkedin-in"
url = "https://www.linkedin.com/in/navin-karkera-407957a0/"
title = "LinkedIn"

[[params.social.list]]
icon = "fab fa-youtube"
url = "https://www.youtube.com/channel/UC6_qlLt9q-o3K5E0Un6eCYw"
title = "YouTube"

[[params.social.list]]
icon = "fab fa-github"
url = "https://github.com/navinkarkera"
title = "GitHub"

[[params.social.list]]
icon = "fab fa-gitlab"
url = "https://gitlab.com/navinkarkera"
title = "Gitlab"

[[params.social.list]]
icon = "fas fa-file-download"
url = "Resume.pdf"
title = "Download PDF"

# Education section
[params.education]
title = "Education"

[[params.education.list]]
degree = "Bachelor of Engineering"
college = "University of Mumbai"
dates = "2011 - 2014"
field = "Electronics and Telecommunication"

[[params.education.list]]
degree = "Diploma"
college = "Maharashtra State Board of Technical Education"
dates = "2008 - 2011"
field = "Industrial Electronics"

# Languages section
[params.language]
title = "Languages"

[[params.language.list]]
language = "English"
level = "Fluent"

[[params.language.list]]
language = "Hindi"
level = "Fluent"

# Interests section
[params.hobbies]
title = "Hobbies"

[[params.hobbies.list]]
interest = "Travelling"

[[params.hobbies.list]]
interest = "Music"

[[params.hobbies.list]]
interest = "Reading"

[params.aboutme]
description = """
I'm a Full Stack developer with experience in creating scalable and
robust applications using Python and Web technologies. Working with both
start-ups and large organisations has prepared me to perform in a variety of
situations.

### [YouTube Channel](https://www.youtube.com/channel/UC6_qlLt9q-o3K5E0Un6eCYw)

_**Name:**_ [ITcracy](https://www.youtube.com/channel/UC6_qlLt9q-o3K5E0Un6eCYw)

You can also find me on YouTube *(not active anymore)*, where my software
developer friend [Ishan Masdekar](https://imasdekar.gitlab.io/) and I share our
expertise in programming languages and other technologies.


### Learning new things

In my spare time, I enjoy learning new technologies such as Rust, Bun and Go, as
well as customising my GNU/Linux setup. I use Neovim as my primary editor and
am always looking for ways to improve it.

---
"""


# Experiences section
[params.experiences]
title = "Experiences"

[[params.jobs.list]]
position = "Senior Open Source Developer (Remote)"
dates = "March 2022 - *Present*"
link = "https://opencraft.com/"
company = "OpenCraft"
details = """
*Core technologies*: `Python, Typescript, React, and Docker`

We as OpenCraft provide managed hosting for Open edX deployments small enough
to serve small organisations or large enough for a nation state. We also work
on implementing new features and fix bugs in Open edX.

Currently, my responsibility is developing new features for Open edX, like the
new library authoring experience.

*Key Achievements:*

- Built [xblock-skill-tagging](https://github.com/openedx/xblock-skill-tagging)
  Open edX plugin from scratch to automatically tag content in courses and use
  user feedback to verify and finalize them.

- Built [event-bus-redis](https://github.com/openedx/event-bus-redis) from
  scratch which serves as a Redis Streams implementation of Open edX event bus.
  Joined Open edX [Core Contributor](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/core-contributors.html)
  program following this contribution.

- Built [Course outline](https://docs.openedx.org/en/latest/educators/concepts/open_edx_platform/about_course_outline.html)
  functionality using React and Typescript for Open edX Studio.

- Built UI foundation of [Listaflow](https://gitlab.com/opencraft/dev/listaflow)
  using React and redux. Listaflow is an Open Source web application for
  tracking your recurring business practices and checklists.

- Currently, contributing my time to build the new [library
  authoring](https://github.com/openedx/frontend-app-authoring) experience.
"""

[[params.jobs.list]]
position = "Authorized Officer"
dates = "Jan 2018 - Feb 2022"
link = "https://www.ubs.com/"
company = "UBS"
details = """
*Core technologies*: `Python, VueJs and GNU/Linux`

Serving as a key member of the team developing an automated model documentation
solution for the entire division, as well as taking on multiple side projects
such as developing web apps, automating ETL operations, and developing
reporting solutions for various teams.

*Key Achievements:*

- Core developer for the project `DocKit`, a division-wide solution for
  document automation that involves everything from `JupyterLab` plugins to
  smart notebook merging. We're automating the process of model validation and
  confirmation by using `pandoc` to convert from one format to another, such as
  jupyter notebooks to markdown to LaTex, and `Jinja` templates to dynamically
  generate LaTex files. I contribute on the tool's planning, development,
  documentation, and on boarding with clients.

- Using `Python/Pandas/Flask`, developed a reporting system for Risk Weighted
  Assets (RWA) that considerably decreased the cost and time it took to prepare
  reports that were delivered to FED Regulators.

- Developed static and dynamic web pages while working in Agile methodology.
  to construct smart applications utilising tools like FastAPI, VueJs, and
  NLTK/Spacy such as FAQs, share reporting to regulators, and so on.

- Created solutions using Python Airflow, Pandas, and other tools to automate
  ETL-like processes involving Chief Risk Officers, such as reporting of
  shortfalls, violations, and ECN limits, among other things. These were seen
  as a huge aid to the bank during pandemics.

- Learned about data processing and machine learning while working on the
  **data quality** project, which was an attempt to detect data quality
  issues in data received from other banks and manually scanned by Risk
  Officers.

- Managed several deployments on Azure-hosted GNU/Linux machines. Using tools
  like systemd and nginx, I was able to secure the web services. Wherever
  possible, automated deployments utilising bash scripts, python doit, and
  other tools.

- Conducted Python Workshops.

- Won a hackathon and assisted in the organisation of another.

- _**Promoted to Authorized Officer from Employee position.**_.

"""

[[params.jobs.list]]
position = "Senior Software Developer"
dates = "Feb 2017 - Jan 2018"
link = "https://www.bankofamerica.com/"
company = "Bank of America"
details = """
*Core technologies*: `Python, SQL`

Worked for Market Risk team solving architectural design issues and code level
issues. Built complete systems to automate a manual process and also helped
migrating complete projects from Java to Python platform.

*Key Achievements:*

- Initiated a project called Chat-Bot, built it from scratch using NLTK and
  Django rest framework, also integrated it with Skype for Business.

"""

[[params.jobs.list]]
position = "Lead Developer"
dates = "Feb 2015 - Feb 2017"
link = "https://dff.org.in/"
company = "Digital Freedom foundation"
details = """
*Core technologies*: `Python, Postgres, Docker and GNU/Linux`

I began my career as a software developer in a start-up, where I was
responsible for all aspects of a web application, including design,
development, and deployment. GNUKhata, a free and open source accounting and
inventory software, was the project. It was built from the ground up utilising
the `Pyramid Pylons framework`, `bootstrap`, `JQuery`, `Postgres`, `Docker`,
and other tools.

*Key Achievements:*

- In the first two years, I learned the most about Python programming and web
  technologies, and I contributed significantly to the GNUKhata project.

- Learned about containerized environments as part of the process of leveraging
  Docker to make the GNUKhata platform agnostic.

- Along with the DFF team, conducted many FOSS workshops at institutions in
  Maharashtra, India.

"""

# Projects section
[params.projects]
title = "Projects"

[[params.projects.list]]
title = "Dockit"
url = "#"
description = "JupyterLab based documentation solution for building Model validation/confirmation reports using Jinja templates and LaTex"

[[params.projects.list]]
title = "RWA"
url = "#"
description = "Web application to generate multiple reports to be sent to Feds"

[[params.projects.list]]
title = "GNUKhata"
url = "https://gnukhata.in/"
description = "Free & Open Source accounting and inventory software"

# Skills section
[params.skills]
title = "Skills"

[[params.skills.list]]
skill = "Python, Django, FastAPI"
skillrating = 95 # out of 100

[[params.skills.list]]
skill = "Git"
skillrating = 95 # out of 100

[[params.skills.list]]
skill = "Javascript, Typescript, React"
skillrating = 95

[[params.skills.list]]
skill = "Airflow/Prefect"
skillrating = 80

[[params.skills.list]]
skill = "Sql, PostgresSQL"
skillrating = 80

[[params.skills.list]]
skill = "Rust"
skillrating = 40 # out of 100

[[params.skills.list]]
skill = "Go"
skillrating = 40 # out of 100

